
version: '3.7'

services:
  springboot-app:
    image: springboot-jpa-app
    restart: always
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - mysql-docker
    environment:
      MYSQL_HOST: mysql-docker
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

  mysql-docker:
    container_name: mysqldb
    image: mysql:8.0.28
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=spring_jpa
    ports:
      - '3307:3306'
    volumes:
      - "C:/Users/subhjdut/Downloads/spring-boot-data-jpa/src/main/resources/mysql:/var/lib/mysql"