version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "8080:8090"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.26
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: world
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root