
version: '3.7'

services:
  docker-mysql:
    image: mysql:8.0.26
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=world
      - MYSQL_PASSWORD=root
    ports:
      - 3307:3306

  app:
    image: subhojitdutta01/springboot-jpa-image:latest
    ports:
      - 8091:8091
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/world?autoReconnect=true&useSSL=false
    depends_on:
      - docker-mysql